# Generated by Django 4.1.2 on 2022-11-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CentralServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DeanOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DeanOfStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GamesAndSportsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HealthUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('school', models.CharField(choices=[('EDU', 'Education'), ('ASSB', 'Arts, Social Science and Business'), ('INFOCOM', 'Information Communication and Media Studies'), ('SAES', 'Science Agriculture and Environmental Studies')], max_length=50)),
                ('year_of_study', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='University_library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAccommodationsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cleared', models.BooleanField()),
                ('costed_owed', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student')),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.BooleanField()),
                ('dean_of_school', models.BooleanField()),
                ('university_library', models.BooleanField()),
                ('university_accommodations_section', models.BooleanField()),
                ('catering_section', models.BooleanField()),
                ('health_unit', models.BooleanField()),
                ('games_and_sports_office', models.BooleanField()),
                ('dean_of_students', models.BooleanField()),
                ('central_services', models.BooleanField()),
                ('student_finance', models.BooleanField()),
                ('registrar', models.BooleanField()),
                ('finance_officer', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.student')),
            ],
        ),
    ]
