# Generated by Django 4.1.2 on 2022-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('academicYear', models.CharField(max_length=20)),
                ('yearOfStudy', models.CharField(max_length=20)),
            ],
        ),
    ]
