# Generated by Django 4.1.2 on 2022-11-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Ryan', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='second_name',
            field=models.CharField(default='Njoroge', max_length=10),
            preserve_default=False,
        ),
    ]
