# Generated by Django 4.1.2 on 2022-11-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_student_first_name_student_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
