# Generated by Django 4.1.2 on 2022-11-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='academicYear',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='yearOfStudy',
            field=models.IntegerField(max_length=20),
        ),
    ]
