# Generated by Django 4.1.2 on 2022-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_student_info_academicyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='academicYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='yearOfStudy',
            field=models.IntegerField(),
        ),
    ]
