# Generated by Django 4.1.2 on 2022-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_student_info_academicyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='userName',
            field=models.IntegerField(),
        ),
    ]
