# Generated by Django 4.1.2 on 2022-11-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_user_info_password_alter_user_info_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department_info',
            new_name='DepartmentInfo',
        ),
        migrations.RenameModel(
            old_name='School_info',
            new_name='SchoolInfo',
        ),
        migrations.RenameModel(
            old_name='Student_info',
            new_name='StudentInfo',
        ),
        migrations.RenameModel(
            old_name='User_info',
            new_name='UserInfo',
        ),
    ]
