# Generated by Django 4.1.2 on 2022-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_department_info_departmentinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userName',
            field=models.CharField(max_length=20),
        ),
    ]
