# Generated by Django 4.1.2 on 2022-11-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_userinfo_password_alter_userinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='sex',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='academicYear',
            field=models.CharField(max_length=20),
        ),
    ]
