# Generated by Django 4.1.2 on 2022-11-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_studentinfo_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='registration_number',
            new_name='registrationNumber',
        ),
    ]
