# Generated by Django 4.1.2 on 2022-11-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_schoolinfo_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='department_name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.schoolinfo'),
        ),
    ]
