# Generated by Django 4.1.2 on 2022-11-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_departmentinfo_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceSchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentinfo')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.schoolinfo')),
            ],
        ),
    ]
