# Generated by Django 4.1.2 on 2022-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_scienceschoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userEmail',
            field=models.EmailField(default='njorogerae@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
