# Generated by Django 4.1.2 on 2022-11-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_userinfo_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentinfo')),
            ],
        ),
    ]
