# Generated by Django 4.1.2 on 2022-11-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_studentinfo_registrationnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userEmail',
        ),
    ]
